name: Cricket CI/CD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t cricket-website .

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: 13.60.210.54
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd ~/Cricket
            git pull origin main

            docker stop cricket-website || true
            docker rm cricket-website || true

            docker build -t cricket-website .

            docker run -d \
              --name cricket-website \
              -p 80:80 \
              cricket-website

            docker ps
